# Generated by Django 4.0.2 on 2022-02-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patienthistory',
            options={'ordering': ('-recorded_on',)},
        ),
        migrations.RenameField(
            model_name='patienthistory',
            old_name='recored_on',
            new_name='recorded_on',
        ),
    ]
